"""
agents/state.py — Single source of truth for all node data.
New fields vs v2:
  - generated_tests   : auto-generated pytest cases (if user didn't provide)
  - execution_status  : "ok" | "error" — direct python run result
  - execution_output  : stdout/stderr from direct execution
  - error_analysis    : structured LLM diagnosis before each retry
"""

from typing import TypedDict, Optional


class AgentState(TypedDict):
    # ── INPUT ──────────────────────────────────────────────────────────────────
    task: str                        # plain-English description of what to build
    test_code: Optional[str]         # user-provided tests (optional now)
    broken_code: Optional[str]       # optional: user's broken code to fix

    # ── GENERATED BY AGENT ────────────────────────────────────────────────────
    generated_tests: Optional[str]   # auto-generated pytest cases
    code: str                        # current generated/fixed code

    # ── EXECUTION RESULTS ─────────────────────────────────────────────────────
    execution_status: Optional[str]  # "ok" | "error"
    execution_output: Optional[str]  # stdout/stderr from direct run

    # ── TEST RESULTS ──────────────────────────────────────────────────────────
    test_output: Optional[str]       # full pytest stdout
    error_log: Optional[str]         # trimmed error for LLM context

    # ── ANALYSIS ──────────────────────────────────────────────────────────────
    error_analysis: Optional[str]    # structured diagnosis from error_analyzer

    # ── CONTROL ───────────────────────────────────────────────────────────────
    attempt: int                     # how many code generations have run
    max_attempts: int                # ceiling — prevents infinite loop
    status: str                      # "pending" | "success"
